### ISSUE TITLE
ID confict Forestry Tohou_Alice_Dolls

### ISSUE THREAD

**Issue by ThomasRules2000** [NikkyAI/RetroBTM17#4]
The mod touhou_alice_dolls is overwriting existing item at 5256 (forestry.core.items.ItemForestry from Forestry) with mods.touhou_alice_dolls.ItemDollCore

**Comment by NikkyAI** [comment]
i assume you can change the IDs? or is there a complication i am no aware of ?

**Comment by ThomasRules2000** [comment]
It was just a reminder, seems fixed now
